schema_version = "1.9.8"
id = "curve_toolkit"
version = "1.9.8"
name = "Curve Toolkit"
tagline = "Curve modeling tools and bone chain generation"
maintainer = "madan6557"
type = "add-on"
tags = ["Rigging", "Modeling"]
blender_version_min = "4.2.0"
license = [
    "SPDX:GPL-3.0-or-later",
]
