schema_version = "1.0.0"
id = "hair_modeling_toolkit"
version = "1.2.4"
name = "Hair Modeling Toolkit"
tagline = "Curve hair modeling tools and bone chain generation"
maintainer = "madan6557"
type = "add-on"
tags = ["Rigging", "Modeling"]
blender_version_min = "4.2.0"
license = [
    "SPDX:GPL-3.0-or-later",
]
