schema_version = "1.0.0"
id = "bone_to_curve"
version = "1.0.3"
name = "Bone to Curve"
tagline = "Generate bone chains along the active curve path"
maintainer = "madan6557"
type = "add-on"
tags = ["Rigging"]
blender_version_min = "4.2.0"
license = [
    "SPDX:GPL-3.0-or-later",
]
